### ISSUE TITLE
[Diff & Merge] Select file to compare raises an exception (does not work from the command bar)

### ISSUE THREAD

**Issue by GitMensch** [moshfeu/vscode-diff-merge#62]
> Running the contributed command: 'diffMerge.selectToCompare' failed.

I've used this command from the command palette.
It does work when using it on the context menu of a file's toolbar entry.

~~~
[error] TypeError: Cannot read property 'fsPath' of undefined
	at selectToCompare (c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\commands.js:90:30)
	at S._executeContributedCommand (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:106770)
	at S.$executeContributedCommand (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:107208)
	at c._doInvokeHandler (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:12794)
	at c._invokeHandler (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:12478)
	at c._receiveRequest (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:11145)
	at c._receiveOneMessage (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:9931)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:8032
	at _.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at E.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15496)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:30083
	at _.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at E.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15496)
	at t._receiveMessage (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20754)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17640
	at _.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at acceptChunk (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12861)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12209
	at Socket.w (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) diffMerge.selectToCompare
~~~

**Comment by moshfeu** [comment]
Thank you!
The fix includes:
- Select the current editor file if it's a text file (Improvement 👍 )
- Show an error message to let the user know what's wrong
