### ISSUE TITLE
Compare selected files in explorer view seems to be broken on Win32

### ISSUE THREAD

**Issue by GitMensch** [moshfeu/vscode-diff-merge#63]
* go to Explorer-view
* select two files
* open context-menu
* see "[Diff & Merge] Compare selected files" and click on it
* nothing seems to happen

The protocol from extension host shows

~~~
[error] Error: ENOENT: no such file or directory, open '\root\dir\file.ext' 
	at Object.openSync (fs.js:466:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
	at Object.readFileSync (fs.js:368:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
	at getContentOrFallback (c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\content.js:77:26)
	at Object.getExplorerSides (c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\content.js:33:26)
	at c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\commands.js:71:65
	at Generator.next (<anonymous>)
	at c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\commands.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\commands.js:4:12)
	at fileDiff (c:\Users\me\.vscode-oss\extensions\moshfeu.diff-merge-0.5.2\out\commands.js:57:16)
	at S._executeContributedCommand (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:106770)
	at S.$executeContributedCommand (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:107208)
	at c._doInvokeHandler (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:12794)
	at c._invokeHandler (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:12478)
	at c._receiveRequest (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:11145)
	at c._receiveOneMessage (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:9931)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:8032
	at _.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at E.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15496)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:30083
	at _.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at E.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15496)
	at t._receiveMessage (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20754)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17640
	at _.fire (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at acceptChunk (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12861)
	at D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12209
	at Socket.w (D:\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) diffMerge.compareSelected
~~~

The file is located at "X:\root\dir", but the directory path is not in the argument.

**Comment by moshfeu** [comment]
Thank you for noticing!
I don't have a machine with Win32 but I'll try to get one with by a virtual machine.
What version of windows are you using?

**Comment by GitMensch** [comment]
> What version of windows are you using?

Shouldn't matter, I guess it is all the same. The most relevant targets are likely Win10, then Win11, then some Windows server, but as noted this likely happens in all the same way.

**Comment by moshfeu** [comment]
So far I didn't have the chance to work on that so if someone has windows and can help fixing it, that would be awesome.

**Comment by GitMensch** [comment]
Hey bot, that was too fast - it is definitely still an open issue and as many people still use Windows clients likely one that _should_ be fixed and kept open until this is solved.

**Comment by GitMensch** [comment]
Maybe the bot can be adjusted to don't add wontfix labels if another label is in, possibly something like helpwanted.
